name: motorparts_marketplace
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  supabase: ^0.2.14
  cupertino_icons: ^1.0.2
  encrypted_shared_preferences: ^3.0.0
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.3
  auto_size_text: ^3.0.0
  http: ^0.13.4
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
